### PR TITLE
add changes :clock1130:

### PR DESCRIPTION
**Pull request by azat-co**
CC @AnnJohn @vicfriedman

### CODE REVIEW

**Comment by vicfriedman** [comment]
i just ran the tests on the solution branch and its failing...

```  0 passing (97ms)
  1 failing

  1) node account must match the desired output:

      Uncaught AssertionError: expected 'Account before opening:  customerAccountNew balance after signup bonus is 250Account after opening:  { balance: NaN,  name: \'Azat Mardan\',  checking: \'1\',  type: \'savings\' }' to equal 'Account before opening:  { balance: 0, name: \'Azat Mardan\', checking: \'1\' }New balance after signup bonus is 250Account after opening:  { balance: 1250,  name: \'Azat Mardan\',  checking: \'1\',  type: \'checking\' }'
      + expected - actual

      -Account before opening:  customerAccountNew balance after signup bonus is 250Account after opening:  { balance: NaN,  name: 'Azat Mardan',  checking: '1',  type: 'savings' }
      +Account before opening:  { balance: 0, name: 'Azat Mardan', checking: '1' }New balance after signup bonus is 250Account after opening:  { balance: 1250,  name: 'Azat Mardan',  checking: '1',  type: 'checking' }
      
```

**Comment by victhevenot** [comment]
On the solution branch - can we put the actual correct solution in account.js. That way someone helping a student doesn't have to hunt around for the solution and read comments

**Comment by victhevenot** [comment]
i did originally have an older version of node - i went back through the node install lab and there were no instructions on updating. i had to uninstall node and reinstall from nodejs.org. is there any easier way to do this? if so let's include in node-install

**Comment by victhevenot** [comment]
the tests here are really hard to read. students won't know what a child_process is.

We want the tests to be as clear as possible for a student to read and understand what it is they need to do. adding complicated tests adds another layer of complexity for the students. tests are meant to be guides.

is there a way to refactor (even if that means refactoring the lab to make it return as opposed to print to the console) so the tests are more readable?

**Comment by azat-co** [comment]
Updated after the 1st review CC @AnnJohn @vicfriedman 

RE: node versions, the solutions to have multiple versions or switch between them were in that node install lesson from the beginning. ;-)

**Comment by victhevenot** [comment]
This branch looks good - merging solution

`wip-master` doesn't have updated tests or updated readme.

**Pull request merged**
